### ISSUE TITLE
Question with consider type relation 1-n, n-n

### ISSUE THREAD

**Issue by lthlong0310** [MIRALab-USTC/KGE-HAKE#10]
Thank you for your work 
In HAKE, the model has to consider type relation 1-n, n-n?

Looking forword to your reply, thank you.

**Comment by zq0x7a0x71** [comment]
Hi. 

We did not explicitly consider these complex relation types as other popular distance-based models, including TransE and RotatE. However, when training these models, we can implicitly deal with these complex  relations by letting $d_r(h,t_1)=d_r(h,t_2)=...=d_r(h,t_n)$.

You can also see an explanation in the rebuttal of RotatE. [link](https://openreview.net/forum?id=HkgEQnRqYQ&noteId=B1gmLa420X)
