### ISSUE TITLE
I just want to ask one question about code.

### ISSUE THREAD

**Issue by myunghakLee** [MIRALab-USTC/KGE-HAKE#11]
In have a question about the code written in "codes/models.py".
In "codes/models.py", there is an "if statement" as below.
I want to know if there is a reason for dividing the condition with the 'if statement'.

```
        if batch_type == BatchType.HEAD_BATCH:
            phase_score = phase_head + (phase_relation - phase_tail)
        else:
            phase_score = (phase_head + phase_relation) - phase_tail

```

Of course, since it is a float operation, the value is different. 
But this is due to the limitation of the operation device.
So I wonder if there is a logical difference.

Thank you for reading.

**Comment by zq0x7a0x71** [comment]
Logically, they are the same. The "if statement" is used to reduce computational complexity.

For example, if `batch_type=BatchType.TAIL_BATCH`, then the shapes of `phase_head`, `phase_relation`, and `phase_tail` will be `[batch_size, 1, dim]`, `[batch_size, 1, dim]`, and `[batch_size, negative_sample_size, dim]`, respectively. The computational complexity of `phase_head + (phase_relation - phase_tail)` and `(phase_head + phase_relation) - phase_tail` are _2* batch_size * negative_sample_size * dim_ and _batch_size * dim + batch_size * negative_sample_size * dim_, respectively. Obviously, using the implementation `(phase_head + phase_relation) - phase_tail` can reduce computational complexity.
