### ISSUE TITLE
实体层次问题

### ISSUE THREAD

**Issue by chenxn2020** [MIRALab-USTC/KGE-HAKE#12]
你好，我用HAKE得到了实体的embedding。请问我如何根据实体的embedding，判断两个实体是否属于同一层次呢？就是我想问如何利用模型训练好的实体embedding，来区分实体的层级呢？

**Comment by zq0x7a0x71** [comment]
你好，可以通过比较两个实体 modulus embedding 的大小来区分，层级高的会具有较小的 modulus。
