### ISSUE TITLE
Question about HAKE: how is hierarchy considered?

### ISSUE THREAD

**Issue by ricardomokhtari** [MIRALab-USTC/KGE-HAKE#13]
Hello, I have a question about how HAKE models hierarchy in the input graph. Specifically, does the embedding of an entity using HAKE only consider information at a 1-hop distance or is information considered at a multi-hop distance?

For example, if an entity is at the highest level of hierarchy in the graph, does HAKE's embedding of this entity capture information all the way from it's hierarchy down to the lowest level of hierarchy, or is it just considering information at a 1-hop distance?

Thank you!

**Comment by zq0x7a0x71** [comment]
Hi~

When designing HAKE, we only explicitly consider the information at a 1-hop distance. However, the learned modulus embeddings may implicitly capture the multi-hop information.
