### ISSUE TITLE
请问能将该模型用于DBP15K数据集吗？

### ISSUE THREAD

**Issue by JLei67** [MIRALab-USTC/KGE-HAKE#14]
目前用于实体对齐比较多的是DBP15K，但现在DBP15K里貌似没有类似的层级数据

**Comment by zq0x7a0x71** [comment]
1. 模型本身并没有对使用的数据集有任何限制，可以应用于各种知识图谱，当然也包括 DBP15K。
2. 我们在论文中讨论过，在分层现象比较明显的数据集上模型的性能会更好一些。
3. 为达到最优性能，不同数据分布的数据集需要采用不同的超参数，如果应用于 DBP15K 的话需要进行额外的调参。

**Comment by JLei67** [comment]
好的，感谢解答
