### ISSUE TITLE
I'd like to ask about the running environment and running steps

### ISSUE THREAD

**Issue by SemanticInteroperability** [MIRALab-USTC/KGE-HAKE#15]
Hello, I am an undergraduate who has just come into contact with the knowledge map, and I have just read your paper. I would like to ask whether the code is running in Linux environment? Can I run and operate under windows? Second, what are the running steps of the code?

We look forward to your answers~

**Comment by zq0x7a0x71** [comment]
Hi~ We ran all the experiments on Ubuntu. I think the code would work well on Windows if you have properly installed the required packages, while I am not sure the results can be exactly reproduced. On Windows, you may have trouble in running a bash script. So just run the python command inside the `runs.sh` and fill the missing variables manually.

**Comment by SemanticInteroperability** [comment]
Hello, I'm sorry to disturb you again. When I run the code on Ubuntu, I report an error because I installed the CPU version of pytorch. I did not select the CUDA version. Is CUDA required?

**Comment by zq0x7a0x71** [comment]
Yes. CUDA is necessary.
