### ISSUE TITLE
Question about figure 3 visualization

### ISSUE THREAD

**Issue by QuocHuyyCS** [MIRALab-USTC/KGE-HAKE#16]
Hello, I am currently a final year student and I have a graduation project on this knowledge graph topic. I am very impressed with your approach to the problem. I have a question about "Figure 3" in the article, I don't quite understand how to draw this graph. Could you please be more specific about this?
Thank you very much and I look forward to hearing from you

**Comment by zq0x7a0x71** [comment]
Just save the learned relation embeddings and plot the phase part using `matplotlib.pyplot.hist`. You may need to tune the `bins` parameter to obtain a better visual effect.
