### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by wangshu1331** [MIRALab-USTC/KGE-HAKE#17]
Thank you very much for the code! I read your code carefully, I have one  question,I would be grateful if you could help me with the answer
## in data.py:131
``` python
    def collate_fn(data):
        positive_sample = torch.stack([_[0] for _ in data], dim=0)
        negative_sample = torch.stack([_[1] for _ in data], dim=0)
        subsample_weight = torch.cat([_[2] for _ in data], dim=0)
        batch_type = data[0][3]# this line
        return positive_sample, negative_sample, subsample_weight, 
```

this function is processing one batch, all data in this batch have only a kind of batch_type ?

**Comment by jianyucai** [comment]
yes, all data in this batch have only **one** kind of batch_type for convenience.

**Comment by wangshu1331** [comment]
> yes, all data in this batch have only **one** kind of batch_type for convenience.

Thank you for your answer, I have a better understanding of the code！！！
