### ISSUE TITLE
About the hyperparameters

### ISSUE THREAD

**Issue by Zawo1995** [MIRALab-USTC/KGE-HAKE#3]
I find that the hyperparameters from the HAKE is almost the same as RotatE expect the new parameters

- MODULUS_WEIGHT

- PHASE_WEIGHT

Could you explain how you grid seach them?(such as the range of grid search)

**Comment by zhanqiuzhang** [comment]
We search both MODULUS_WEIGHT and PHASE_WEIGHT in {0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0}. Moreover, we find that when MODULUS_WEIGHT>=PHASE_WEIGHT, the performance could be better, so we only do a grid-search for this case.
