### ISSUE TITLE
Number of parameters 

### ISSUE THREAD

**Issue by Demirrr** [MIRALab-USTC/KGE-HAKE#5]
Hello,

I was wondering where one could find the number of parameters of the ModE and HAKE on WN18RR, FB15k-237 and YAGO3-10.

Cheers

**Comment by zhanqiuzhang** [comment]
Hi,

The number of parameters can be calculated by d_e * E+d_r * R, where d_e is the entity embedding dimension, E is the number of entities, d_r is the relation embedding dimension, and R is the number of relations. You can find the values of d_e,  d_r, E, and R in README and our paper.

Also, you can download the codes and initialize the model with Pytorch, and then print the number of parameters ([How do I check the number of parameters of a model?](https://discuss.pytorch.org/t/how-do-i-check-the-number-of-parameters-of-a-model/4325)).

Regards

**Comment by Demirrr** [comment]
Life would more beautiful if everyone answers questions as precise as @zhanqiuzhang :). Appreciated!

**Comment by zhanqiuzhang** [comment]
You can find the results on page 14 of [Sun et al. (2019)](https://arxiv.org/abs/1902.10197).

**Comment by Demirrr** [comment]
Oh I see, results are provided in the appendix.
