### ISSUE TITLE
Why don't you compare with Poincare embedding ?

### ISSUE THREAD

**Issue by Woooooody** [MIRALab-USTC/KGE-HAKE#6]
As we all know, Poincare embeddings main contribution is representation hierarchy struct data in hyperbolic space.

**Comment by zhanqiuzhang** [comment]
To the best of our knowledge, the first paper that embeds knowledge graphs into hyperbolic space is [1]. However, when we submitted our paper to AAAI 2020, [1] has not been published, and we were not aware of its existence.

Nonetheless, you can see that our HAKE outperforms the methods in [1] by a large margin. 

[1] Balazevic, Ivana, Carl Allen, and Timothy Hospedales. "Multi-relational Poincaré graph embeddings." Advances in Neural Information Processing Systems. 2019.
