### ISSUE TITLE
For the phase part, why divided by two?

### ISSUE THREAD

**Issue by chuanyang-Zheng** [MIRALab-USTC/KGE-HAKE#7]
For the phase part, why the model score function is sin((h+p-t)/2). If possible, could you please tell us why you divide the (h+p-t) by 2?

**Comment by zhanqiuzhang** [comment]
We use |sin((h+p-t)/2)| in the phase part for the following two reasons.

a) Phases are periodic. The sine function can reflect the periodicity.
b) The possible distance between two phases is in [0, pi]. Thus, the score function should be monotonically increasing in [0, pi], which corresponds to the division of 2 in the score function.

**Comment by chuanyang-Zheng** [comment]
The h, p, t are between [-pi, pi]. Hence, h+p-t are between [-3pi, 3pi]. Therefore, **why the possible distance between the two phases is in [0, pi]**? Thank you for your reply.

**Comment by zhanqiuzhang** [comment]
As I described before, phases are periodic. Thus, even though h+p-t can be in [-3pi, 3pi], the distance between h+p and t is always in [0, pi]. For example, if h+p-t=3pi, then the actual distance is pi; if h+p-t=3pi/2, then the distance is pi/2.
